### ISSUE TITLE
Can I use this library on the raspberry pi

### ISSUE THREAD

**Issue by opemipoVRB** [adafruit/Adafruit_CircuitPython_PCA9685#1]
I want to control things like duty cycle and all but the library for the raspberry pi doesn't seem to have that would this work?

**Comment by tannewt** [comment]
No, sorry. We'd like to build a layer underneath our CircuitPython libraries so they can run on raspberry pi but we haven't yet.

**Comment by opemipoVRB** [comment]
So how can I control the speed of my servo on raspberry pi with the PCA9685 16channel 12 bit PWM LED & servo driver

**Comment by opemipoVRB** [comment]
Any Suggestion ?

**Comment by tannewt** [comment]
This isn't the right place to get support for it (the forums are). However, it looks like you should use `set_pwm_freq` to adjust the length of the PWM on cycle. For analog servos, that should be enough. I don't think they care about the overall frequency. They just care about the length of the on pulse.

Please follow up in the support forums if you have further questions: https://forums.adafruit.com/viewforum.php?f=50
