### ISSUE TITLE
Can pycharm be used as a simulator to run developed programs?

### ISSUE THREAD

**Issue by DLHoldguy2015** [adafruit/Adafruit_CircuitPython_PCA9685#22]
Currently I use Pycharm to develop code to run on the Raspberry Pi ( R Pi ).  Using PUTTY I transfer the code to the R Pi  to test.  
Is there any way to use Pycharm to test this code before I transfer it to the R Pi?

**Comment by ladyada** [comment]
nope, we cant simulate hardwaer, you need to run this code directly on a pi :)

**Comment by DLHoldguy2015** [comment]
Thanks for the response.
