### ISSUE TITLE
Mpy file needs to be refreshed

### ISSUE THREAD

**Issue by fede2cr** [adafruit/Adafruit_CircuitPython_PCA9685#3]
I was trying to use this module as released in a 2.0.0 version of CircuitPython but the module says it's incompatible with the version.

I asked in Discord an was suggested to open an incident to ask the module to be "refreshed" so it can work with the latest version.

Following the error message, I did tried the module released in the Bundle and it is now working perfectly. I also noted the message in the module release notes that it is compatible with CircuitPython 0.9.4.

Thanks.

**Comment by tdicola** [comment]
Thanks for catching and mentioning it!  I just bumped to a 2.0 release that caused a new .mpy to be generated.  See the latest 2.0 release in the releases tab, or grab from the latest bundle like you saw too.
