### ISSUE TITLE
[doc] Example of servo sweep is wrong

### ISSUE THREAD

**Issue by jvalrog** [adafruit/Adafruit_CircuitPython_PCA9685#35]
The code for that example is wrong. It lacks delays so the sweep is useless.

The example file is this: https://github.com/adafruit/Adafruit_CircuitPython_PCA9685/blob/master/examples/pca9685_servo.py

And it differs from this other one from the Motor library (it's actually the same example but this one has delays): https://github.com/adafruit/Adafruit_CircuitPython_Motor/blob/master/examples/motor_pca9685_servo_sweep.py

**Comment by ladyada** [comment]
hi please submit a PR for a version with delays then

**Comment by jposada202020** [comment]
Closed by #36
