### ISSUE TITLE
No control of MODE2 register

### ISSUE THREAD

**Issue by User8230** [adafruit/Adafruit_CircuitPython_PCA9685#38]
There isn't a way to control the MODE2 register. The fix is pretty easy.

**WAS**

    # Registers:
    mode1_reg = UnaryStruct(0x00, "<B")

**IS**

    # Registers:
    mode1_reg = UnaryStruct(0x00, "<B")
    mode2_reg = UnaryStruct(0x01, "<B")

See:  [https://forums.adafruit.com/viewtopic.php?f=19&t=160780&p=790983&hilit=PCA9685+MODE2#p790983](url)

**Comment by tekktrik** [comment]
Hi @User8230, I've added access to this register if you want to close the issue!
