### ISSUE TITLE
duty_cycle getter doesn't return what setter was given

### ISSUE THREAD

**Issue by DrRob** [adafruit/Adafruit_CircuitPython_PCA9685#52]
Hi, why does the setter have `value + 1` in line 91?:

`value = (value + 1) >> 4`

There isn't a corresponding adjustment in the getter, so for example if I set duty_cycle to 0x7fff and then read it back I get 0x8000.

Thanks!
Rob.

**Comment by tekktrik** [comment]
@tannewt Looks like this was in the original commit for the library, curious if you know or remember why the getter and setter would be different?

**Comment by tannewt** [comment]
I don't remember. Sorry!

It would make more sense to read the same value back.

**Comment by tekktrik** [comment]
Thanks @tannewt!

Looks like it might be a bug @DrRob, are you interested in submitting a PR to fix it?

**Comment by DrRob** [comment]
I'll try, but I'm puzzled about why the `value + 1` part doesn't result in a requested duty cycle of zero actually being on for 1/4096th of the period.  (It doesn't - I checked with an oscilloscope.)

**Comment by DrRob** [comment]
Actually I got that wrong - if a duty cycle of zero is requested, then `(0 + 1) >> 4` == `1 >> 4` == 0, so both the LEDn_ON and LEDn_OFF registers are set to zero, which probably explains why the output is off all the time as expected...

...HOWEVER, the datasheet says, "The LEDn_ON and LEDn_OFF count registers should never be programmed with the same values."  LEDn_OFF should be set to 0x1000 for fully off.

I'll try to fix it according to the datasheet instructions.

**Comment by DrRob** [comment]
I'm a bit rusty with git but I think I've just submitted a PR for this.
